#!/bin/sh
#
# AUTHOR: aichp
#
# DATE: 2017-09-22
#
# DESC: Elvi to open diepresse
# elvis: diepresse		-- open diepresse (http://diepresse.com/)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] 
Description:
  open diepresse (http://diepresse.com/)
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt=$1
    optarg=$2
    case $opt in
	-results=*) setopt   $SURFRAW_results $optarg	;;
	*) return 1 ;;
    esac
    return 
}
w3_config
w3_parse_args $@
if test -z $w3_args; then
    w3_browse_url http://diepresse.com/
else
   
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url http://diepresse.com//${escaped_args}



fi
