#!/bin/sh
#
# AUTHOR: aichp
#
# DATE: 2017-11-12
#
# DESC: Elvi to open discord
# elvis: discord		-- open discord (https://discordapp.com/login?redirect_to=%2F)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] 
Description:
  open discord (https://discordapp.com/login?redirect_to=%2F)
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt=$1
    optarg=$2
    case $opt in
	-results=*) setopt   $SURFRAW_results $optarg	;;
	*) return 1 ;;
    esac
    return 
}
w3_config
w3_parse_args $@
if test -z $w3_args; then
    w3_browse_url https://discordapp.com/login?redirect_to=%2F
else
   
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url https://discordapp.com/login?redirect_to=%2F/${escaped_args}



fi
