#!/bin/sh
#
# AUTHOR: aichp
#
# DATE: 2017-09-18
#
# DESC: Elvi to open duden
# elvis: duden		-- open duden (http://www.duden.de/suchen/dudenonline/)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] 
Description:
  open duden (http://www.duden.de/suchen/dudenonline/)
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt=$1
    optarg=$2
    case $opt in
	-results=*) setopt   $SURFRAW_results $optarg	;;
	*) return 1 ;;
    esac
    return 
}
w3_config
w3_parse_args $@
if test -z $w3_args; then
    w3_browse_url http://www.duden.de/suchen/dudenonline/
else
   
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url http://www.duden.de/suchen/dudenonline/${escaped_args}



fi
