#!/bin/sh
#
# AUTHOR: aichp
#
# DATE: 2018-03-21
#
# DESC: Elvi to open fhmail
# elvis: fhmail		-- open fhmail (mail.fh-ooe.at)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] 
Description:
  open fhmail (mail.fh-ooe.at)
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt=$1
    optarg=$2
    case $opt in
	-results=*) setopt   $SURFRAW_results $optarg	;;
	*) return 1 ;;
    esac
    return 
}
w3_config
w3_parse_args $@
if test -z $w3_args; then
    w3_browse_url mail.fh-ooe.at
else
   
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url mail.fh-ooe.at/${escaped_args}



fi
