#!/bin/sh
#
# AUTHOR: aichp
#
# DATE: 2018-01-02
#
# DESC: Elvi to open oberbank
# elvis: oberbank		-- open oberbank (https://www.banking-oberbank.at/)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] 
Description:
  open oberbank (https://www.banking-oberbank.at/)
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt=$1
    optarg=$2
    case $opt in
	-results=*) setopt   $SURFRAW_results $optarg	;;
	*) return 1 ;;
    esac
    return 
}
w3_config
w3_parse_args $@
if test -z $w3_args; then
    w3_browse_url https://www.banking-oberbank.at/
else
   
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url https://www.banking-oberbank.at//${escaped_args}



fi
